kind: pipeline
name: badge-backend

steps:
- name: build
  image: plugins/docker
  settings:
    repo: sybex/badgeservice
    tags:
      - latest
      - 1.1.${DRONE_BUILD_NUMBER}
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

- name: deploy
  image: sinlead/drone-kubectl
  settings:
    kubernetes_server:
      from_secret: kubernetes_server_url
    kubernetes_token:
      from_secret: kubernetes_server_token
  commands:
    - kubectl apply -f deployment.yaml

- name: notify
  image: appleboy/drone-telegram
  when:
    status:
    - success
    - failure
  settings:
    token:
      from_secret: pipeline_bot
    to: 146910928

